#!/usr/bin/env bash

set -euo pipefail

echo "--delete bucket"

if [ -z "${1:-}" ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi

BUCKET="$1"

aws s3api delete-bucket \
  --bucket "$BUCKET"

echo "✅ Bucket '$BUCKET' deleted"
