#!/usr/bin/env bash

set -euo pipefail

echo "--list objects in bucket"

if [ -z "${1:-}" ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi

BUCKET="$1"

aws s3api list-objects-v2 \
  --bucket "$BUCKET"

echo " listing the objects in Bucket '$BUCKET' "