AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  EmailProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EmailProcessor
      Runtime: python3.13
      Handler: app.lambda_handler
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      # 👇 ADD THIS BLOCK TO FIX THE SQS PERMISSIONS
      Policies:
        - AWSLambdaSQSQueueExecutionRole